### ISSUE TITLE
IPv4 (192.168.199.0 / 24) network segment can communicate, but intranet (192.168.1.0 / 24) cannot communicate!

### ISSUE THREAD

**Issue by shaozhai** [JonStratton/mesh-front-py#11]
IPv4 (192.168.199.0 / 24) network segment can communicate, but intranet (192.168.1.0 / 24) cannot communicate!

![image](https://user-images.githubusercontent.com/3293135/98460028-776b3080-21db-11eb-865b-f329da183ba2.png)
![image](https://user-images.githubusercontent.com/3293135/98460033-881ba680-21db-11eb-9825-f36c181f5f28.png)
![image](https://user-images.githubusercontent.com/3293135/98460041-9b2e7680-21db-11eb-9b97-a5354fd3e801.png)

**Comment by shaozhai** [comment]
![image](https://user-images.githubusercontent.com/3293135/98460084-0b3cfc80-21dc-11eb-9e3d-82113f8821cd.png)
![image](https://user-images.githubusercontent.com/3293135/98460086-13953780-21dc-11eb-9ec8-caa65c009b27.png)

**Comment by JonStratton** [comment]
It looks like neither of your nodes is set up to act as an "network (internet) gateway". Please see "Batman Mesh - Adding an network (internet) gateway" in the documentation. 

Hint; the device with the internet connection should be configured to share it with the "Share Internet Uplink" where the interface with the internet connection is selected. This devise should also be configured to be a dhcp server on the bat0 interface. The Node without the internet connection should have bat0 configured to have "Mesh Interface Type" set to dhcp.

**Comment by JonStratton** [comment]
Note, I just released a version that drastically simplifies the configuration (as most of the options were not really used). There is new documentation in the README that goes with this new way to configure.
