### ISSUE TITLE
Wireless-channel setting ignored in Ubuntu

### ISSUE THREAD

**Issue by oblende** [JonStratton/mesh-front-py#3]
As the title says. The wireless-channel setting seems to be ignored in Ubuntu and possibly Debian. Currently working around this by setting channel in /etc/rc.local.

**Comment by JonStratton** [comment]
@oblende , I haven't been able to get olsr to run on a modern version of Ubuntu at all. I'm just getting a "No Interfaces detected" error when launching with either the default configuration, or the one I tweaked from hsmm-pi. Did you happen to test and get things working with just the tweaks you are suggesting?

**Comment by oblende** [comment]
I'm using the Armbian variant of Ubuntu, which may be part of the solution.
I'm not sure. I've recently discovered that my problem is the
NetworkManager service. Disabling this service will allow the channel to be
adjusted as it should be in the /etc/network/interfaces file. Also the
wireless device is no longer called wlan0, it gets renamed during boot for
some unknown user unfriendly reason. I think they felt left out with how
BSD(M) names devices. Also your script when it pulls the OLSRD sources from
git grabs the most recent version. This works, but two of the plugins have
a slight name change.

**Comment by JonStratton** [comment]
Yeah, it seems network manager is possibly causing multiple issues where its installed. Ill try disabling it and maybe installing "net-tools" to get /etc/network/interfaces working on modern Ubuntu.

**Comment by JonStratton** [comment]
I've added some stuff to the installer to better deal with Desktop systems running Network Manager(which should fix the channel issue). This should work better on Ubuntu based systems now (I didn't have access to anything Armbian runs on). 

Again, thanks for the information.
